CREATE TABLE IF NOT EXISTS users(
   id VARCHAR(36) PRIMARY KEY,
   name VARCHAR (150) NOT NULL,
   balance BIGINT DEFAULT 0 NOT NULL,
   cpf VARCHAR (11) UNIQUE,
   cnpj VARCHAR (14) UNIQUE,
   email VARCHAR (50) UNIQUE NOT NULL,
   user_type VARCHAR (10) NOT NULL,
   password VARCHAR(100) NOT NULL,
   active BOOLEAN DEFAULT TRUE NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);