global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'simplified-wallet'
    static_configs:
      - targets: ['host.docker.internal:3000']  # For Docker on Mac/Windows
    # If running in Linux, use:
    # - targets: ['app:3000']  # Assuming your app service is named 'app'